# Домашнее задание по теме «Рекомендации на основе содержания»

Построить рекомендации (регрессия, предсказываем оценку) на фичах:  
1. TF-IDF на тегах и жанрах  
2. Средние оценки (+ median, variance, etc.) пользователя и фильма  
3. Оценить RMSE на тестовой выборке

In [12]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np

from tqdm.notebook import tqdm

from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
from sklearn.neighbors import NearestNeighbors

%matplotlib inline

In [2]:
# links = pd.read_csv('links.csv')
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')
tags = pd.read_csv('tags.csv')

In [3]:
ratings

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [4]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [5]:
tags

      userId  movieId               tag   timestamp
0          2    60756             funny  1445714994
1          2    60756   Highly quotable  1445714996
2          2    60756      will ferrell  1445714992
3          2    89774      Boxing story  1445715207
4          2    89774               MMA  1445715200
...      ...      ...               ...         ...
3678     606     7382         for katie  1171234019
3679     606     7936           austere  1173392334
3680     610     3265            gun fu  1493843984
3681     610     3265  heroic bloodshed  1493843978
3682     610   168248  Heroic Bloodshed  1493844270

[3683 rows x 4 columns]

In [6]:
def change_string(s):
    return ' '.join(s.replace(' ', '').replace('-', '').split('|'))

In [13]:
# tfidf по жанрам

temp_df = pd.DataFrame(TfidfTransformer().fit_transform(CountVectorizer().fit_transform(movies.genres.to_list())).toarray())

movies.loc[:, 'genres'] = movies.loc[:, 'genres'].apply(lambda x: change_string(x))
movies.loc[:, temp_df.columns.tolist()] = temp_df.loc[:,:]
movies

,movieId,title,genres,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
0,1,Toy Story (1995),AdventureAnimationChildrenComedyFantasy,0.000000,0.416846,0.516225,0.504845,0.267586,0.0,0.0,0.000000,0.482990,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Jumanji (1995),AdventureChildrenFantasy,0.000000,0.512361,0.000000,0.620525,0.000000,0.0,0.0,0.000000,0.593662,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Grumpier Old Men (1995),ComedyRomance,0.000000,0.000000,0.000000,0.000000,0.570915,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.821009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale (1995),ComedyDramaRomance,0.000000,0.000000,0.000000,0.000000,0.505015,0.0,0.0,0.466405,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.726241,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Father of the Bride Part II (1995),Comedy,0.000000,0.000000,0.000000,0.000000,1.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),ActionAnimationComedyFantasy,0.436010,0.000000,0.614603,0.000000,0.318581,0.0,0.0,0.000000,0.575034,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9738,193583,No Game No Life: Zero (2017),AnimationComedyFantasy,0.000000,0.000000,0.682937,0.000000,0.354002,0.0,0.0,0.000000,0.638968,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9739,193585,Flint (2017),Drama,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9740,193587,Bungo Stray Dogs: Dead Apple (2018),ActionAnimation,0.578606,0.000000,0.815607,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,0.000000,0.000000,0.000000,0.000000,1.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
# считаем метрики для рейтинга, проставленного пользователем

users_ratings = pd.DataFrame([ratings.groupby('userId').rating.mean()
                              , ratings.groupby('userId').rating.median()
                              , ratings.groupby('userId').rating.std()
                              , ratings.groupby('userId').rating.var()
                             ]
                            ).T.reset_index()
users_ratings.columns = ['userId', 'u_mean', 'u_median', 'u_std', 'u_var']
users_ratings

     userId    u_mean  u_median     u_std     u_var
0         1  4.366379       5.0  0.800048  0.640077
1         2  3.948276       4.0  0.805615  0.649015
2         3  2.435897       0.5  2.090642  4.370783
3         4  3.555556       4.0  1.314204  1.727132
4         5  3.636364       4.0  0.990441  0.980973
..      ...       ...       ...       ...       ...
605     606  3.657399       4.0  0.724121  0.524351
606     607  3.786096       4.0  0.965657  0.932494
607     608  3.134176       3.0  1.079262  1.164807
608     609  3.270270       3.0  0.450225  0.202703
609     610  3.688556       3.5  0.857422  0.735173

[610 rows x 5 columns]

In [9]:
# считаем метрики для рейтинга, проставленный фильмам

movies_ratings = pd.DataFrame([ratings.groupby('movieId').rating.mean()
                              , ratings.groupby('movieId').rating.median()
                              , ratings.groupby('movieId').rating.std()
                              , ratings.groupby('movieId').rating.var()
                             ]
                            ).T.reset_index()
movies_ratings.columns = ['movieId', 'm_mean', 'm_median', 'm_std', 'm_var']
movies_ratings

      movieId    m_mean  m_median     m_std     m_var
0           1  3.920930       4.0  0.834859  0.696990
1           2  3.431818       3.5  0.881713  0.777419
2           3  3.259615       3.0  1.054823  1.112651
3           4  2.357143       3.0  0.852168  0.726190
4           5  3.071429       3.0  0.907148  0.822917
...       ...       ...       ...       ...       ...
9719   193581  4.000000       4.0       NaN       NaN
9720   193583  3.500000       3.5       NaN       NaN
9721   193585  3.500000       3.5       NaN       NaN
9722   193587  3.500000       3.5       NaN       NaN
9723   193609  4.000000       4.0       NaN       NaN

[9724 rows x 5 columns]

In [95]:
# tfidf по тегам (уменьшаем размерность с 1400+ до 20 фичей)

from sklearn.decomposition import PCA

movies_tags = tags.groupby('movieId').tag.apply(lambda x: ' '.join([change_string(str(i)) for i in x.to_list()])).reset_index()

pca = PCA(n_components=20)
pca.fit(TfidfTransformer().fit_transform(CountVectorizer().fit_transform(movies_tags.tag.to_list())).toarray().T)

temp_df = pd.DataFrame(pca.components_.T)

movies_tags.loc[:, temp_df.columns.tolist()] = temp_df.loc[:,:]
movies_tags

,movieId,tag,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1,pixar pixar fun,-0.000095,0.002419,-0.000514,-0.000044,-0.000373,-0.000782,0.000849,0.000202,-0.000529,-0.000481,-0.000405,-0.000518,-0.000260,-0.000565,-0.000548,-0.001193,-0.000460,-0.000870,-0.000961,-0.001369
1,2,fantasy magicboardgame RobinWilliams game,-0.000139,-0.000397,-0.000631,-0.000486,-0.000372,-0.000532,-0.000410,-0.000990,-0.000713,-0.000259,-0.000476,-0.000500,-0.000357,-0.000491,-0.001122,-0.001419,-0.000646,-0.001096,-0.001235,-0.001104
2,3,moldy old,-0.000097,-0.000281,-0.000387,-0.000282,-0.000203,-0.000293,-0.000352,-0.000644,-0.000436,-0.000286,-0.000380,-0.000252,-0.000148,-0.000119,-0.000586,-0.000907,-0.000573,-0.000823,-0.000975,-0.000830
3,5,pregnancy remake,-0.000103,-0.000526,0.011343,-0.000702,-0.000289,-0.001415,0.000959,-0.000189,-0.000087,-0.003060,-0.001636,-0.003100,-0.003617,-0.007497,0.006030,0.002019,0.009241,0.002582,0.010581,0.000991
4,7,remake,-0.000074,-0.000400,0.000336,-0.000935,-0.000288,-0.001315,0.001026,-0.000179,0.000010,-0.002159,-0.001420,-0.003195,-0.004210,-0.008264,0.006733,0.003116,0.012380,0.004971,0.015457,0.000923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1567,183611,Comedy funny RachelMcAdams,-0.000126,0.000290,-0.001012,0.010275,0.000146,-0.000674,-0.001332,-0.002441,-0.001307,-0.001410,0.000450,0.002514,-0.004490,-0.006218,0.002810,-0.002998,-0.000482,0.012132,-0.002342,-0.017451
1568,184471,adventure AliciaVikander videogameadaptation,-0.000120,-0.000332,-0.000578,-0.000440,-0.000333,-0.000530,-0.000309,-0.000852,-0.000667,-0.000136,-0.000479,-0.000431,-0.000389,-0.000851,-0.001301,-0.000960,-0.000478,-0.001309,-0.001422,-0.000976
1569,187593,JoshBrolin RyanReynolds sarcasm,-0.000121,-0.000379,-0.000504,-0.000526,-0.000460,-0.000971,0.001164,0.000384,-0.000505,-0.000498,-0.000436,-0.000415,-0.000290,-0.000318,-0.000489,-0.001207,-0.000484,-0.000878,-0.001333,-0.001391
1570,187595,EmiliaClarke starwars,-0.000098,-0.000293,-0.000345,-0.000320,-0.000216,-0.000331,-0.000349,-0.000682,-0.000329,-0.000263,-0.000403,-0.000265,-0.000165,-0.000287,-0.000690,-0.000906,-0.000532,-0.000615,-0.000558,-0.000871
1571,193565,anime comedy gintama remaster,-0.000111,-0.000443,-0.000982,0.000005,-0.000500,-0.000777,-0.001356,-0.002960,-0.001793,0.004413,-0.001748,0.003982,-0.005359,-0.014172,-0.005727,-0.001150,-0.000221,0.011957,-0.010788,-0.009181

In [96]:
# соединяем датафреймы

resultdf = pd.merge(ratings
                    , movies
                    , on = 'movieId'
                   )

resultdf = pd.merge(resultdf
                    , users_ratings
                    , on = 'userId'
                   )

resultdf = pd.merge(resultdf
                    , movies_ratings
                    , on = 'movieId'
                   )

resultdf = pd.merge(resultdf
                    , movies_tags
                    , on = 'movieId'
                   )

resultdf

,userId,movieId,rating,timestamp,title,genres,0_x,1_x,2_x,3_x,4_x,5_x,6_x,7_x,8_x,9_x,10_x,11_x,12_x,13_x,14_x,15_x,16_x,17_x,18_x,19_x,20,21,22,23,u_mean,u_median,u_std,u_var,m_mean,m_median,m_std,m_var,tag,0_y,1_y,2_y,3_y,4_y,5_y,6_y,7_y,8_y,9_y,10_y,11_y,12_y,13_y,14_y,15_y,16_y,17_y,18_y,19_y
0,1,1,4.0,964982703,Toy Story (1995),AdventureAnimationChildrenComedyFantasy,0.000000,0.416846,0.516225,0.504845,0.267586,0.000000,0.0,0.000000,0.48299,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,4.366379,5.0,0.800048,0.640077,3.92093,4.00,0.834859,0.69699,pixar pixar fun,-0.000095,0.002419,-0.000514,-0.000044,-0.000373,-0.000782,0.000849,0.000202,-0.000529,-0.000481,-0.000405,-0.000518,-2.597235e-04,-0.000565,-0.000548,-0.001193,-0.000460,-0.000870,-0.000961,-0.001369
1,5,1,4.0,847434962,Toy Story (1995),AdventureAnimationChildrenComedyFantasy,0.000000,0.416846,0.516225,0.504845,0.267586,0.000000,0.0,0.000000,0.48299,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,3.636364,4.0,0.990441,0.980973,3.92093,4.00,0.834859,0.69699,pixar pixar fun,-0.000095,0.002419,-0.000514,-0.000044,-0.000373,-0.000782,0.000849,0.000202,-0.000529,-0.000481,-0.000405,-0.000518,-2.597235e-04,-0.000565,-0.000548,-0.001193,-0.000460,-0.000870,-0.000961,-0.001369
2,7,1,4.5,1106635946,Toy Story (1995),AdventureAnimationChildrenComedyFantasy,0.000000,0.416846,0.516225,0.504845,0.267586,0.000000,0.0,0.000000,0.48299,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,3.230263,3.5,1.329594,1.767820,3.92093,4.00,0.834859,0.69699,pixar pixar fun,-0.000095,0.002419,-0.000514,-0.000044,-0.000373,-0.000782,0.000849,0.000202,-0.000529,-0.000481,-0.000405,-0.000518,-2.597235e-04,-0.000565,-0.000548,-0.001193,-0.000460,-0.000870,-0.000961,-0.001369
3,15,1,2.5,1510577970,Toy Story (1995),AdventureAnimationChildrenComedyFantasy,0.000000,0.416846,0.516225,0.504845,0.267586,0.000000,0.0,0.000000,0.48299,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,3.448148,3.5,1.133404,1.284605,3.92093,4.00,0.834859,0.69699,pixar pixar fun,-0.000095,0.002419,-0.000514,-0.000044,-0.000373,-0.000782,0.000849,0.000202,-0.000529,-0.000481,-0.000405,-0.000518,-2.597235e-04,-0.000565,-0.000548,-0.001193,-0.000460,-0.000870,-0.000961,-0.001369
4,17,1,4.5,1305696483,Toy Story (1995),AdventureAnimationChildrenComedyFantasy,0.000000,0.416846,0.516225,0.504845,0.267586,0.000000,0.0,0.000000,0.48299,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,4.209524,4.0,0.508490,0.258562,3.92093,4.00,0.834859,0.69699,pixar pixar fun,-0.000095,0.002419,-0.000514,-0.000044,-0.000373,-0.000782,0.000849,0.000202,-0.000529,-0.000481,-0.000405,-0.000518,-2.597235e-04,-0.000565,-0.000548,-0.001193,-0.000460,-0.000870,-0.000961,-0.001369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48282,309,7218,4.5,1086564148,"Ox-Bow Incident, The (1943)",DramaWestern,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.335734,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.941957,0.000000,0.0,0.0,0.941957,3.839806,4.0,0.802000,0.643204,4.50000,4.50,NaN,NaN,InNetflixqueue,0.094164,0.000060,0.000084,0.000185,-0.001235,-0.000007,0.000010,0.000043,0.000071,0.000035,0.000082,-0.000047,8.734686e-07,-0.001408,0.000035,0.000179,-0.000085,-0.000012,-0.000105,-0.001043
48283,356,44889,5.0,1229140843,Reefer Madness: The Movie Musical (2005),ComedyDramaMusical,0.000000,0.000000,0.000000,0.000000,0.381788,0.000000,0.0,0.352599,0.00000,0.0,0.0,0.0,0.854349,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,4.020761,4.0,0.743900,0.553387,4.75000,4.75,0.353553,0.12500,satire,-0.000074,-0.000354,0.003400,-0.000387,-0.000347,-0.000558,-0.000371,-0.000843,-0.000654,-0.000827,-0.000032,-0.000735,-6.610447e-04,-0.001257,0.000149,-0.000826,0.000342,0.000094,-0.001216,-0.001831
48284,538,44889,4.5,1307846820,Reefer Madness: The Movie Musical (2005),ComedyDramaMusical,0.000000,0.000000,0.000000,0.000000,0.381788,0.000000,0.0,0.352599,0.00000,0.0,0.0,0.0,0.854349,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,4.472973,4.5,0.588618,0.346471,4.75000,4.75,0.353553,0.12500,satire,-0.000074,-0.000354,0.003400,-0.000387,-0.000347,-0.000558,-0.000371,-0.000843,-0.000654,-0.000827,-0.000032,-0.000735,-6.610447e-04,-0.001257,0.000149,-0.000826,0.000342,0.000094,-0.001216,-0.001831
48285,125,5088,5.0,1474141620,"Going Places (Valseuses, Les) (1974)",ComedyCrimeDrama,0.000000,0.000000,0.000000,0.000000,0.478734,0.758507,0.0,0.442132,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,3.859722,4.0,0.802444,0.643916,5.00000,5.00,NaN,NaN,irreverent,-0.000070,-0.000243,0.003716,-0.000166,-0.000150,-0.000295,-0.000276,-0.000503,-0.000373,-0.000326,-0.000135,-0.000281,-1.693986e-04,-0.000240,-0.000416,-0.000756,-0.000377,-0.000439,-0.000925,-0.000863
48286,184,193565,3.5,1537098554,Gintama: The Movie (2010),ActionAnimationComedySciFi,0.445376,0.000000,0.627805,0.000000,0.325424,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.549181,0.0,0.0,0.000000,0.481367,0.0,0.0,0.000000,3.705224,4.0,1.067660,1.139897,3.50000,3.50,NaN,NaN,anime comedy gintama remaster,-0.000111,-0.000443,-0.000982,0.000005,-0.000500,-0.000777,-0.001356,-0.002960,-0.001793,0.004413,-0.001748,0.003982,-5.358747e-03,-0.014172,-0.005727,-0.001150,-0.000221,0.011957,-0.010788,-0.009181

In [97]:
# нанов мало, поэтому просто удаляем строки + дропаем столбцы
data = resultdf.iloc[:, 2:].copy()
data = data[data.notna().all(axis=1)][data.dtypes[(data.dtypes == float) | (data.dtypes == int)].index.tolist()]
data

,rating,0_x,1_x,2_x,3_x,4_x,5_x,6_x,7_x,8_x,9_x,10_x,11_x,12_x,13_x,14_x,15_x,16_x,17_x,18_x,19_x,20,21,22,23,u_mean,u_median,u_std,u_var,m_mean,m_median,m_std,m_var,0_y,1_y,2_y,3_y,4_y,5_y,6_y,7_y,8_y,9_y,10_y,11_y,12_y,13_y,14_y,15_y,16_y,17_y,18_y,19_y
0,4.0,0.0,0.416846,0.516225,0.504845,0.267586,0.0,0.0,0.000000,0.48299,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.00000,0.0,4.366379,5.0,0.800048,0.640077,3.92093,4.00,0.834859,0.69699,-0.000095,0.002419,-0.000514,-0.000044,-0.000373,-0.000782,0.000849,0.000202,-0.000529,-0.000481,-0.000405,-0.000518,-2.597235e-04,-0.000565,-0.000548,-0.001193,-0.000460,-0.000870,-0.000961,-0.001369
1,4.0,0.0,0.416846,0.516225,0.504845,0.267586,0.0,0.0,0.000000,0.48299,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.00000,0.0,3.636364,4.0,0.990441,0.980973,3.92093,4.00,0.834859,0.69699,-0.000095,0.002419,-0.000514,-0.000044,-0.000373,-0.000782,0.000849,0.000202,-0.000529,-0.000481,-0.000405,-0.000518,-2.597235e-04,-0.000565,-0.000548,-0.001193,-0.000460,-0.000870,-0.000961,-0.001369
2,4.5,0.0,0.416846,0.516225,0.504845,0.267586,0.0,0.0,0.000000,0.48299,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.00000,0.0,3.230263,3.5,1.329594,1.767820,3.92093,4.00,0.834859,0.69699,-0.000095,0.002419,-0.000514,-0.000044,-0.000373,-0.000782,0.000849,0.000202,-0.000529,-0.000481,-0.000405,-0.000518,-2.597235e-04,-0.000565,-0.000548,-0.001193,-0.000460,-0.000870,-0.000961,-0.001369
3,2.5,0.0,0.416846,0.516225,0.504845,0.267586,0.0,0.0,0.000000,0.48299,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.00000,0.0,3.448148,3.5,1.133404,1.284605,3.92093,4.00,0.834859,0.69699,-0.000095,0.002419,-0.000514,-0.000044,-0.000373,-0.000782,0.000849,0.000202,-0.000529,-0.000481,-0.000405,-0.000518,-2.597235e-04,-0.000565,-0.000548,-0.001193,-0.000460,-0.000870,-0.000961,-0.001369
4,4.5,0.0,0.416846,0.516225,0.504845,0.267586,0.0,0.0,0.000000,0.48299,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.00000,0.0,4.209524,4.0,0.508490,0.258562,3.92093,4.00,0.834859,0.69699,-0.000095,0.002419,-0.000514,-0.000044,-0.000373,-0.000782,0.000849,0.000202,-0.000529,-0.000481,-0.000405,-0.000518,-2.597235e-04,-0.000565,-0.000548,-0.001193,-0.000460,-0.000870,-0.000961,-0.001369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48261,2.5,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.391730,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.92008,0.0,0.000000,0.0,0.92008,0.0,3.020175,3.0,0.793779,0.630084,3.75000,3.75,1.767767,3.12500,0.094164,0.000060,0.000084,0.000185,-0.001235,-0.000007,0.000010,0.000043,0.000071,0.000035,0.000082,-0.000047,8.734686e-07,-0.001408,0.000035,0.000179,-0.000085,-0.000012,-0.000105,-0.001043
48266,2.5,0.0,0.451542,0.000000,0.546866,0.289859,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.416834,0.489162,0.0,0.00000,0.0,0.439408,0.0,0.00000,0.0,3.924668,4.0,0.917981,0.842689,3.50000,3.50,1.414214,2.00000,-0.000069,-0.000199,-0.000274,-0.000199,-0.000144,-0.000207,-0.000249,-0.000455,-0.000308,-0.000202,-0.000268,-0.000178,-1.042876e-04,-0.000084,-0.000414,-0.000641,-0.000405,-0.000582,-0.000689,-0.000587
48267,4.5,0.0,0.451542,0.000000,0.546866,0.289859,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.416834,0.489162,0.0,0.00000,0.0,0.439408,0.0,0.00000,0.0,3.881720,4.0,0.818363,0.669718,3.50000,3.50,1.414214,2.00000,-0.000069,-0.000199,-0.000274,-0.000199,-0.000144,-0.000207,-0.000249,-0.000455,-0.000308,-0.000202,-0.000268,-0.000178,-1.042876e-04,-0.000084,-0.000414,-0.000641,-0.000405,-0.000582,-0.000689,-0.000587
48283,5.0,0.0,0.000000,0.000000,0.000000,0.381788,0.0,0.0,0.352599,0.00000,0.0,0.0,0.0,0.854349,0.0,0.0,0.000000,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.00000,0.0,4.020761,4.0,0.743900,0.553387,4.75000,4.75,0.353553,0.12500,-0.000074,-0.000354,0.003400,-0.000387,-0.000347,-0.000558,-0.000371,-0.000843,-0.000654,-0.000827,-0.000032,-0.000735,-6.610447e-04,-0.001257,0.000149,-0.000826,0.000342,0.000094,-0.001216,-0.001831
48284,4.5,0.0,0.000000,0.000000,0.000000,0.381788,0.0,0.0,0.352599,0.00000,0.0,0.0,0.0,0.854349,0.0,0.0,0.000000,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.00000,0.0,4.472973,4.5,0.588618,0.346471,4.75000,4.75,0.353553,0.12500,-0.000074,-0.000354,0.003400,-0.000387,-0.000347,-0.000558,-0.000371,-0.000843,-0.000654,-0.000827,-0.000032,-0.000735,-6.610447e-04,-0.001257,0.000149,-0.000826,0.000342,0.000094,-0.001216,-0.001831

In [98]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:]
                                                    , data.rating
                                                    , test_size=0.2
                                                    , random_state=42)

In [99]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression().fit(X_train, y_train)

In [100]:
lr.score(X_train, y_train)

0.28494996292814356

In [101]:
from sklearn.metrics import mean_squared_error

y_pred = lr.predict(X_test)

mean_squared_error(y_test, y_pred)

0.6514941412438606

Скор - не вау. Отклонение - тоже, но в принципе еще терпимо) наверняка можно улучшить, повозившись с фичами